import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { BackLink, LegalSection, P, UL } from '@/components/ui/Legal';

const EFFECTIVE_DATE = 'June 27, 2026';
const COMPANY = 'Apt-Intel';
const EMAIL = 'privacy@chatseller.dev';
const APP_NAME = 'ChatSeller';

export default function PrivacyPolicy() {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div className="legal-wrap">
      <div className="wrap legal-page">
        <BackLink />
        <span className="section-label" style={{ marginTop: '1.5rem', marginBottom: '1.5rem' }}>Legal</span>
        <h1 className="legal-h1">Privacy Policy</h1>
        <p className="legal-meta">Effective date: {EFFECTIVE_DATE} &nbsp;·&nbsp; {COMPANY}</p>

        <LegalSection title="1. Who We Are">
          <P>
            {COMPANY} ("we", "us", "our") operates {APP_NAME}, an AI sales chat automation platform. Our registered business
            address is in Nigeria. For privacy inquiries, contact us at <a href={`mailto:${EMAIL}`}>{EMAIL}</a>.
          </P>
          <P>This Privacy Policy explains how we collect, use, store, and protect information when you or your customers interact with {APP_NAME}.</P>
        </LegalSection>

        <LegalSection title="2. Information We Collect">
          <P><strong>2.1 Business Account Information</strong></P>
          <P>When you register as a business on ChatSeller, we collect:</P>
          <UL items={[
            'Business name, email address, and contact phone number',
            'Business category, description, and operating hours you provide',
            'Product catalog data you upload (names, prices, images, descriptions)',
            'Knowledge base content you upload (PDFs, URLs, FAQ text)',
            'Billing and subscription information (payment details handled by our payment processors)',
          ]} />

          <P><strong>2.2 Customer Conversation Data</strong></P>
          <P>When your customers chat with your business through your ChatSeller widget, we process:</P>
          <UL items={[
            'A device-generated visitor identifier for the customer (no phone number required to start a chat)',
            'Message content sent to and from the widget',
            'Timestamps and delivery status of messages',
            'Where the customer came from (e.g. a tagged link shared on social media or your website)',
            'Order details captured during AI-assisted conversations',
            'Customer intent classifications generated by our AI pipeline',
          ]} />
          <P>We do not collect the personal identity of your end customers beyond what they voluntarily share in the chat (such as a name or delivery phone number for an order).</P>

          <P><strong>2.3 Usage and Technical Data</strong></P>
          <UL items={[
            'Dashboard login events and feature usage analytics',
            'API request logs for debugging and performance monitoring',
            'Browser type and device information for dashboard and widget users',
            'IP addresses for security and fraud prevention',
          ]} />
        </LegalSection>

        <LegalSection title="3. How We Use Your Information">
          <P>We use the data we collect to:</P>
          <UL items={[
            'Operate the ChatSeller platform and deliver AI-powered responses to your customers',
            "Train and maintain the AI models that power your business's knowledge base and catalog retrieval",
            'Send you operational notifications (e.g., new orders, AI escalation alerts) via email and your dashboard',
            'Process billing and manage your subscription',
            'Detect and prevent abuse, fraud, and policy violations',
            "Improve ChatSeller's AI accuracy and response quality across the platform",
            'Comply with legal obligations, including requests from regulatory authorities',
          ]} />
          <P>We do <strong>not</strong> sell your data or your customers' data to third parties. We do not use your customer conversation data to train AI models for other businesses.</P>
        </LegalSection>

        <LegalSection title="4. Data Storage and Security">
          <P>Your data is stored on MongoDB Atlas (European region) and Cloudinary for media files. We apply the following security measures:</P>
          <UL items={[
            'All data in transit is encrypted using TLS 1.2 or higher',
            'API credentials and payment secrets are stored encrypted at rest using AES-256',
            'Passwords are hashed using bcrypt with appropriate work factors',
            'Access to production databases is restricted to authorised engineers via VPN',
            'We conduct regular security reviews and dependency audits',
          ]} />
          <P>Despite these measures, no system is completely secure. We encourage you to use strong, unique passwords for your ChatSeller dashboard account.</P>
        </LegalSection>

        <LegalSection title="5. Data Retention">
          <UL items={[
            'Business account data is retained for the duration of your subscription and 90 days after cancellation',
            'Customer conversation logs are retained for 12 months by default; you can request earlier deletion',
            'Order records are retained for 7 years to comply with applicable financial record-keeping requirements',
            'Analytics aggregates are retained indefinitely in anonymised form',
            'Deleted accounts have their personally identifiable data purged within 30 days',
          ]} />
        </LegalSection>

        <LegalSection title="6. Third-Party Services">
          <P>ChatSeller integrates with the following third-party services, each with their own privacy policies:</P>
          <UL items={[
            'MongoDB Atlas — primary database (EU region)',
            'Cloudinary — media and image storage',
            'Paystack — payment processing for Nigerian businesses (where applicable)',
            "OpenAI / Anthropic — AI language model inference (messages may be processed by these providers' APIs in accordance with their data processing agreements)",
          ]} />
        </LegalSection>

        <LegalSection title="7. Your Rights">
          <P>As a business account holder, you have the right to:</P>
          <UL items={[
            'Access all data we hold about your account',
            'Request correction of inaccurate data',
            'Request deletion of your account and associated data',
            'Export your conversation history and catalog data in JSON format',
            'Opt out of non-essential analytics collection',
          ]} />
          <P>
            Your customers (end users interacting via your chat widget) have the right to request deletion of their conversation
            history. You are responsible for handling such requests from your customers and may submit deletion requests on
            their behalf to <a href={`mailto:${EMAIL}`}>{EMAIL}</a>.
          </P>
        </LegalSection>

        <LegalSection title="8. Children's Privacy">
          <P>
            ChatSeller is a B2B platform intended for use by registered businesses. We do not knowingly collect information
            from individuals under the age of 18. If you believe a minor has used your business's ChatSeller widget to
            interact with the AI, please contact us and we will delete the relevant records.
          </P>
        </LegalSection>

        <LegalSection title="9. Changes to This Policy">
          <P>
            We may update this Privacy Policy from time to time. We will notify you of material changes via email and/or a
            notice on your dashboard. Continued use of ChatSeller after a change constitutes acceptance of the updated policy.
            The effective date at the top of this page always reflects the current version.
          </P>
        </LegalSection>

        <LegalSection title="10. Contact Us">
          <P>For privacy-related inquiries, data requests, or complaints:</P>
          <div className="legal-contact-box">
            <div><span>Email: </span><a href={`mailto:${EMAIL}`}>{EMAIL}</a></div>
            <div><span>Company: </span>{COMPANY}</div>
            <div><span>Response time: </span>Within 5 business days</div>
          </div>
        </LegalSection>

        <div className="legal-footer-links">
          <Link to="/terms">Terms of Service →</Link>
          <Link to="/about">About ChatSeller →</Link>
        </div>
      </div>
    </div>
  );
}
